### ISSUE TITLE
crown computation 

### ISSUE THREAD

**Issue by parkygis** [VUKOZ-OEL/3d-forest-classic#14]
Hello,
I just test only one tree and noticed that it takes more than 30 mins to perform crown segmentation.  my cpu i9 with 64g memory.  
I wonder there is installation issue or not.  is that normal to take that long?

**Comment by janekT** [comment]
Hi its really long time for computation. not sure why it takes so much time, but you can make manual crown segmentation -  just remove points that belongs to the stem of tree. Crown starts in the division of the first branch. hope it helps you

**Comment by parkygis** [comment]
thanks for the response.  I guess there were too many points.   after I reduced points, it worked really well.  
once again thanks for your helps.
