### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by petrasvestartas** [VUKOZ-OEL/3d-forest-classic#4]
Hi, 
I am windows .NET user, I would really like to use your software, but I can only see the source code.
Is there any possibility to load pointcloud via command line and retrieve a result in a file?

I also tried to build the source code from cmake, but since I am not good with C++ I do not know how to resolve the errors:
![build](https://user-images.githubusercontent.com/18013985/68535626-d8a0bf80-034d-11ea-8fff-e227cf0f9276.png)

**Comment by janekT** [comment]
Hi, command line interface Is in progress a shoul be part od next release. 
For second problem... You need to Havel installed qt.in cmake find location od qr5widget.cmake file. Usually Its in lib/cmake directory of your install of Qt.

**Comment by petrasvestartas** [comment]
Thank you for the relply. I will try to install qt.

Could you advice how to approach this issue.
I have fairly simple tree forks that I scan with Lidar:
https://vimeo.com/372045079

How could I find centtal axis of such geometry?
I am struggling to find explanation how skeleton is found for such forking. Could you advice me on this problem?

**Comment by janekT** [comment]
Yes you will need to install some dependency like PCL library, qt, Eigen VTK, FLANN or libLAS (hope I mentioned all of them) and include them in Cmake. 

For your second question. axis can be found using many solution. our solution is to make cylinders around small parts of stem and make connection of cylinder centers. But you need to divide stem and branches before. - for this we use method called tree reconstruction.

**Comment by wllfx** [comment]
Hi. I'm new on this informatic world. Is there any tutorial about how to install all the dependency needed?
I'm a Windows user

**Comment by Loris-L** [comment]
> Hi. I'm new on this informatic world. Is there any tutorial about how to install all the dependency needed?
> I'm a Windows user

There is the "README.txt" in source code with the instructions to compile the dependencies

**Comment by wllfx** [comment]
Thank you I found it.
