### ISSUE TITLE
Getting VTK related errors

### ISSUE THREAD

**Issue by tanajikamble13** [VUKOZ-OEL/3d-forest-classic#6]
Getting following errors: 
`/home/tan/project/pcl_work/3DForest/sourceCode/mainwindow.cpp:6496:12: error: ‘const class pcl::visualization::AreaPickingEvent’_ has no member named ‘getActors’
   if(event.getActors (actors) == false)
            ^
/home/tan/project/pcl_work/3DForest/sourceCode/mainwindow.cpp:6509:11: error: ‘const class pcl::visualization::AreaPickingEvent’ has no member named ‘getActorsIndices’
     event.getActorsIndices(cam_it->second.actor, indices);
           ^
/home/tan/project/pcl_work/3DForest/sourceCode/mainwindow.cpp: In member function ‘void MainWindow::pointEvent(const pcl::visualization::PointPickingEvent&, void*)’:
/home/tan/project/pcl_work/3DForest/sourceCode/mainwindow.cpp:6593:27: error: ‘const class pcl::visualization::PointPickingEvent’ has no member named ‘getProp’
   vtkProp3D* prop = event.getProp();
`
The errors are self explanatory. Please update working code

**Comment by janekT** [comment]
IT Is problem with version of pcl.... Please try to compile  pcl version from this repository https://github.com/janekT/pcl
